package view;
import model.Employee;
import view.StatiscalManage;
import dao.statdetailfilmDAO;
import dao.statfilmDAO;
import static java.awt.PageAttributes.MediaType.D;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import model.statShowTime;
import model.statfilm;

/**
 *
 * @author van hieu
 */
public class stabyfilmFrm extends javax.swing.JFrame {


    private Employee em;


    
    public DefaultTableModel tmMH;

    public stabyfilmFrm(Employee em) {

        initComponents();
        this.em = em;
        initTable();

    }



    private void initTable() {

        String[] clos1 = {"ma", "ten", "nhom", "gia"};
        tmMH = new DefaultTableModel(new Object[][]{
            {100, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
                new String[]{
                    "ma", "ten", "nhom,", "gia"
                });
        System.out.println(tmMH.toString());
        //tmMH=new DefaultTableModel();trong fcuoxjj song cuas chungs ta khog cos cai gf id f la fla alflf alaf laflafds laf laf aflaflalf alf aflaflalf alfdsasldfjsaijrwoeirxncsajhfoaiiowrsknfseivsdkhffiuihfvcxcls asdtrogcisongcua chungta khong phair thuwgif quan trong at thuej uwj la vayth nungngyuowif ncos ther godducoj mhanchawm tu trong ,at phutkhong bet boj noi cos gfi maf fonhanh thr enhi 
        //jTable1=new JTable(tmMH);
        jTable1.setModel(tmMH);
        System.err.println("xin chao");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sdate = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        edate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống kê doanh thu theo phim trong khoảng thời gian");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ngày bắt đầu");
        jPanel1.add(jLabel2);

        sdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdateActionPerformed(evt);
            }
        });
        jPanel1.add(sdate);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ngày kết thúc");
        jPanel1.add(jLabel3);
        jPanel1.add(edate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void changedate() {
        String result = "";
        try {
            String s1, s2;
            s1 = sdate.getDate().toString();
            s2 = edate.getDate().toString();
            DateFormat df = new SimpleDateFormat("yyyy-mm-dd");
            // JOptionPane.showMessageDialog(null,df.format(sdate.getDate()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "không được để trông ");

        }
    }

    private void sdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdateActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX()); // get the coloum of the button
        int row = evt.getY() / jTable1.getRowHeight(); // get the row of the button
        if (row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0) {
            JOptionPane.showMessageDialog(null, row);
           int term=(int) jTable1.getValueAt(row, 0);
            statdetailfilmDAO statf = new statdetailfilmDAO();
            ArrayList<statShowTime> listf;
            listf = statf.searchfilm(sdate.getDate(), edate.getDate(),term);

            String[] columnNames = {"Xuất chiếu", "Name", "Tong ve", "doanh thu"};
            String[][] value = new String[listf.size()][4];
            for (int i = 0; i < listf.size(); i++) {
                value[i][0] = listf.get(i).getId() + "";
                value[i][1] = listf.get(i).getName();
                value[i][2] = listf.get(i).getTicket() + "";
                value[i][3] = listf.get(i).getIncome() + "";
            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            jTable1.setModel(tableModel);

        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JButton btnClicked = (JButton) evt.getSource();
        if (btnClicked.equals(jButton1)) {
            //JOptionPane.showMessageDialog(null,"xin chao mọi người");
            changedate();
            statfilmDAO statf = new statfilmDAO();
            ArrayList<statfilm> listf;
            listf = statf.searchfilm(sdate.getDate(), edate.getDate());

            String[] columnNames = {"Id", "Name", "Tong ve", "doanh thu"};
            String[][] value = new String[listf.size()][4];
            for (int i = 0; i < listf.size(); i++) {
                value[i][0] = listf.get(i).getId() + "";
                value[i][1] = listf.get(i).getName();
                value[i][2] = listf.get(i).getTicket() + "";
                value[i][3] = listf.get(i).getIncome() + "";
            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            jTable1.setModel(tableModel);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker edate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker sdate;
    // End of variables declaration//GEN-END:variables
}
